### PR TITLE
fix syntax error and fixed version

### LINKED ISSUE #19: setup.py Bug report
https://github.com/desh2608/diarizer/blob/6a5f9c6848175a9862defe3ae9f1fc7afd117920/setup.py#L88

I think maybe you're missing a comma in this line (?

### PR DESCRIPTION
**Pull request by DTDwind**
Hi,
 
I add a comma and fixed `numpy` version because if `numpy==1.24.2` then `numexpr` and `dscore` will get error.

### CODE REVIEW

**Comment by desh2608** [comment]
Thanks. Could you give an example of what error and at which line in the code?

**Comment by DTDwind** [comment]
EX1: setup.py", line 86
image
EX2: setup.py", line 70
image
image
image
image

**Comment by desh2608** [comment]
It's been a while since I worked on this codebase. I don't remember exactly where `numexpr` is being used. It may be possible to just remove it from the dependency?

**Comment by DTDwind** [comment]
I guess you are using `numexpr` because it is a requirement for `VBx`, but I didn't see them use this library in the `VBx` code, so maybe it's safe to try removing it.

https://github.com/BUTSpeechFIT/VBx/blob/master/requirements.txt#L4

So... should I modify my pull request?

**Comment by desh2608** [comment]
Yeah. Could make this change instead of the numpy version in setup.py?

**Comment by DTDwind** [comment]
Ok

**Comment by DTDwind** [comment]
Maybe we can also remove `numexpr` from the `requirements.txt`?

**Comment by DTDwind** [comment]
Done.

**Review by desh2608 — APPROVED** [review]
LGTM.

**Pull request merged**
